### ISSUE TITLE
mono & Linux

### ISSUE THREAD

**Issue by htho** [thijse/Arduino-Libraries#15]
Hi,

I'd like to use CmdMessanger with Linux.

My Arduino devices are listed as `/dev/ttyACM*`

`_serialTransport.CurrentSerialSettings.PortNameCollection` Does not list these devices. It does not seem to be a rights problem, as starting the Program as root does not help either. I also created a symlink `sudo ln -s /dev/ttyACM0 /dev/ttySACM0` which got listed. Using this Symlink works but is no permanent solution.

According to this Bug report, this seems to be a mono Problem:
https://bugzilla.novell.com/show_bug.cgi?id=795366#c0

Anyway. I don't think I am the only Linux user, who to uses CmdMessanger. How do you solve this issue?

**Comment by thijse** [comment]
Mono Linux is now working!
