### ISSUE TITLE
Spaces vs tabs

### ISSUE THREAD

**Issue by uino** [thijse/Arduino-Libraries#20]
Hi,
Great library, thanks!

One quick comment: the header file looks ugly, because of tabulations issues:
==========
    void 	 setMemPool(int base, int memSize);
	void  	 setMaxAllowedWrites(int allowedWrites);
	int 	 getAddress(int noOfBytes);
	uint8_t  read(int);	
	bool 	 readBit(int, byte);
	uint8_t  readByte(int);
    uint16_t readInt(int);
    uint32_t readLong(int);
	float    readFloat(int);
	double   readDouble(int);	
    bool     write(int, uint8_t);
	bool 	 writeBit(int , uint8_t, bool);
==========

Btw, the now widely-adopted convention adopted by the majority of recent large-scale projects is to use spaces instead of tabs. 

Best,
Arthur

**Comment by thijse** [comment]
I've converted everything to spaces. Concerning the alignment, what I see above looks OK.
