### ISSUE TITLE
Float and Double incorrect due localization settings Windows

### ISSUE THREAD

**Issue by sfrijnts** [thijse/Arduino-Libraries#21]
Double and Floats representation are depending on the system localization settings. The parse uses this representation settings.

See:
http://stackoverflow.com/questions/1354924/how-do-i-parse-a-string-with-a-decimal-point-to-a-double

Problem can be fixed by changing line 160 and 178 in ReceivedCommand to:
if (float.TryParse(_arguments[_parameter], System.Globalization.NumberStyles.Any, CultureInfo.InvariantCulture, out current))

**Comment by thijse** [comment]
Thanks! I've made the changes
